# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
	v.memory = 512
	v.linked_clone = true
  end

  # centos server
  config.vm.define "centos" do |os|
	os.vm.box = "geerlingguy/centos7"
	os.vm.hostname = "centos.test"
	os.vm.network :private_network, ip: "192.168.60.4"
  end

  # ubuntu server
  config.vm.define "ubuntu" do |os|
	os.vm.box = "hashicorp/bionic64"
        os.vm.hostname = "ubuntu.test"
        os.vm.network :private_network, ip: "192.168.60.5"
  end

end
